In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
park = pd.read_csv('./data/서울시/서울시 주요 공원현황.csv', encoding='cp949')
df = park.drop(['연번', '공원개요', '개원일', '주요식물', '안내도', '오시는길','이미지', '관리부서', '전화번호', '바로가기',
          'X좌표(GRS80TM)', 'Y좌표(GRS80TM)', '이용시참고사항', '주요시설'], axis=1)

In [ ]:
df[:5]

,공원명,면적,지역,공원주소,X좌표(WGS84),Y좌표(WGS84)
0,남산도시자연공원,2896887㎡ 임 야 : 2454140㎡ 녹지대 및 기타시설 : 442747㎡,중구,서울특별시 중구 삼일대로 231(예장동),126.990377,37.550140
1,길동생태공원,80683㎡,강동구,서울특별시 강동구 천호대로 1291(길동생태공원),127.154779,37.540394
2,서울대공원,9132690m²,과천시,경기도 과천시 대공원광장로 102,127.019846,37.426449
3,서울숲,480994㎡,성동구,서울특별시 성동구 뚝섬로 273 (성수동1가),127.041798,37.543072
4,월드컵공원,2284085㎡,마포구,서울특별시 마포구 하늘공원로 84(월드컵공원),126.878907,37.571805

In [ ]:
# 공원주소 칼럼 지우기 전 지역 데이터 추출
df[df['지역'].isna()]

       공원명       면적   지역             공원주소  X좌표(WGS84)  Y좌표(WGS84)
129  경춘선숲길  211392㎡  NaN  노원구 공릉2동 산 82-2  127.076482   37.627077

In [ ]:
df['지역'][129] = '노원구'
df.drop('공원주소', axis=1, inplace=True)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_15352\2519024436.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['지역'][129] = '노원구'

In [ ]:
# df[df['X좌표(WGS84)'].isna()]

In [ ]:
df.drop([131], inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   공원명         131 non-null    object
 1   면적          129 non-null    object
 2   지역          131 non-null    object
 3   X좌표(WGS84)  131 non-null    float64
 4   Y좌표(WGS84)  131 non-null    float64
dtypes: float64(2), object(3)
memory usage: 5.2+ KB

In [ ]:
df[df['면적'].isna()]

           공원명   면적   지역  X좌표(WGS84)  Y좌표(WGS84)
109      푸른수목원  NaN  구로구  126.824070   37.483029
119  문화역 서울284  NaN   중구  126.971592   37.555872

In [ ]:
df['면적'][109] = '103,354㎡'
df.drop(119, inplace=True)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_15352\2115178686.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['면적'][109] = '103,354㎡'

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df['면적'].values

array(['2896887㎡ 임 야 : 2454140㎡ 녹지대 및 기타시설 : 442747㎡', '80683㎡',
       '9132690m²', '480994㎡', '2284085㎡', '8948.1㎡',
       '휴양 및 편익시설 : 평의자 7개 화장실 23.18㎡ 조경시설 - 은하폭포(높이 12m × 폭10m 발원지로부터 17.3m 폭 1.5 ~ 10m 수조 255㎡ 담수량 140t) - 산성폭포(높이 5m×폭 12m 수조 90㎡ 담수량 75t)- 명속의 벽 1개소(높이 5.4m) 교양시설 : 야외공연무대 102㎡ 관리시설 : 관리실 8.55㎡ 전기실 51.03㎡ 기계실 83.36㎡ 안내판 1개 공원 등 18본 휴양시설 : 벤취 12개 ',
       '6456㎥',
       '80309㎡ 배수지 시설용량 : 201.000㎥ 송수 펌프용량 : 직송급수계통 30000㎥/일 금호배수지계통 16400㎥/일 ',
       '1980.4㎡   ', '5197.7㎡ ', '11467㎡ ', '229539㎡', '15179.7 ㎡ ',
       '16734.60㎥ ', '61544㎡ 녹지대 : 40792㎡ 광 장 : 6600㎡ 기 타 : 14152㎡',
       '424106㎡ ', '560552㎡', '26696.8㎥ ', '75900㎡', '113021.7m2',
       '201779㎥ ', '258991㎡   ', '10420819.08㎡', '171294.1㎥', '총 15000㎡',
       '297926㎡', '411972㎡', '98470㎡', '2038741.3㎡', '603715.2㎡',
       '108120㎡', '29619.3㎥', '29843.8㎡ ', '126026㎡ ', '135002.7㎡ ',
       '384026㎡ ', '180000㎥', '416031㎡ ', '160720㎡', '2277252㎡ ',
       '19599.70㎥ ', '138596㎡ ', '185295㎥ ', '254648㎡', '29816.5㎡ ',
       '762642㎡ ', '664905㎡ ', '99599.9㎡ ', '5802㎡ ', '총 16500㎥ ',
       '585652㎥ ', '649709.6㎡ ', '72132㎡', '66027.8㎡', '265582㎡',
       '2088704.9㎡', '112070㎡', '993724㎡',
       '219167㎡ 곰두리체육센터 : 7370㎡(지하2층 지상3층) 송파도서관 : 8259㎡(지하1층 지상4층) ',
       '1349556.4㎡ ', '1511198㎡', '1097565㎡', '328018㎡', '총 1447122㎡',
       '207790㎡ ', '1018689㎡', '954553㎡', '1667848㎡', '13224㎡', '130345㎡',
       '5332422㎡', '5107964㎡', '47832㎡', '213552㎡', '168099.87㎡',
       '359435.2㎡', '36660㎡', '380735㎡ ', '1807420.9㎡', '359342.8㎡',
       '632733㎡', '328018㎡', '6691885.3㎡', '285757㎡', '110407㎡',
       '29682.2㎡', '137759㎡', '917190㎡', '51470㎡', '662543㎡', '217946㎡',
       '179666㎥', '34955㎡', '18083㎡', '4835㎡', '19650 ㎡', '7000㎡',
       '10712㎡', '17182㎡', '160349.3㎡', '87432.4㎡', '13467㎡   ', '46871㎡',
       '49972㎡', '74385㎡', '8868㎡ ', '10634㎡ ', '22113㎡', '103,354㎡',
       '1082847㎡', '3692455㎡   ', '386500㎡', '23450㎡', '2400833㎡',
       '2752421㎡', '4180551㎡', '147859㎡', '111650㎡', '519782㎡ ',
       '59347㎡ ', '25500㎡ ', '2560㎡ ', '32000㎡ ', '45615㎡ ', '631021㎡ ',
       '109635㎡ ', '140022㎡', '211392㎡', '157535㎡'], dtype=object)

In [ ]:
df[df['면적'].apply(len) > 12]

,index,공원명,면적,지역,X좌표(WGS84),Y좌표(WGS84)
0,0,남산도시자연공원,2896887㎡ 임 야 : 2454140㎡ 녹지대 및 기타시설 : 442747㎡,중구,126.990377,37.550140
6,6,진관근린공원(구파발폭포),휴양 및 편익시설 : 평의자 7개 화장실 23.18㎡ 조경시설 - 은하폭포(높이 1...,은평구,126.919216,37.637024
8,8,응봉공원,80309㎡ 배수지 시설용량 : 201.000㎥ 송수 펌프용량 : 직송급수계통 30...,성동구,127.021765,37.557228
15,15,영등포근린공원,61544㎡ 녹지대 : 40792㎡ 광 장 : 6600㎡ 기 타 : 14152㎡,영등포구,126.910662,37.515423
59,59,오금근린공원,219167㎡ 곰두리체육센터 : 7370㎡(지하2층 지상3층) 송파도서관 : 825...,송파구,127.132396,37.503872

In [ ]:
df['면적'][0] = '2896887㎡'
df['면적'][6] = '983.791㎡'
df['면적'][8] = '80309㎡'
df['면적'][15] = '61544㎡'
df['면적'][59] = '219167㎡'

C:\Users\Administrator\AppData\Local\Temp\ipykernel_15352\4167455664.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['면적'][0] = '2896887㎡'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_15352\4167455664.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['면적'][6] = '983.791㎡'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_15352\4167455664.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['면적'][8] = '80309㎡'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_15352\4167455664.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['면적'][15] = '61544㎡'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_15352\4167455664.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['면적'][59] = '219167㎡'

In [ ]:
df['면적'] = df['면적'].str.extract(r'(\d+[.]?\d)').astype('float')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       130 non-null    int64
 1   공원명         130 non-null    object
 2   면적          130 non-null    float64
 3   지역          130 non-null    object
 4   X좌표(WGS84)  130 non-null    float64
 5   Y좌표(WGS84)  130 non-null    float64
dtypes: float64(3), int64(1), object(2)
memory usage: 6.2+ KB

In [ ]:
df[:8]

   index            공원명         면적    지역  X좌표(WGS84)  Y좌표(WGS84)
0      0       남산도시자연공원  2896887.0    중구  126.990377   37.550140
1      1         길동생태공원    80683.0   강동구  127.154779   37.540394
2      2          서울대공원  9132690.0   과천시  127.019846   37.426449
3      3            서울숲   480994.0   성동구  127.041798   37.543072
4      4          월드컵공원  2284085.0   마포구  126.878907   37.571805
5      5      광화문시민열린마당     8948.1   종로구  126.978023   37.575045
6      6  진관근린공원(구파발폭포)      983.7   은평구  126.919216   37.637024
7      7        중마루근린공원     6456.0  영등포구  126.911267   37.519832